---
services:
  app:
    container_name: civi-api-exporter
    build: .
    environment:
      DEBUG: ${DEBU:-falseG}
      CIVICRM_BASE_URL: ${CIVICRM_BASE_URL}
      CIVICRM_API_KEY: ${CIVICRM_API_KEY}
      CIVICRM_SEARCHKIT_QUERIES: ${CIVICRM_SEARCHKIT_QUERIES}
    ports:
      - 127.0.0.1:5000:5000
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    read_only: true
